import type { Shipment, Transporter, Bid } from "./types"

export const mockTransporters: Transporter[] = [
  {
    id: "t1",
    role: "transporter",
    name: "James Banda",
    phone: "+265 991 234 567",
    whatsapp: "+265 991 234 567",
    rating: 4.8,
    totalRatings: 156,
    verified: true,
    verificationLevel: "rtoa",
    rtoaMembership: "RTOA-2021-0456",
    vehicleType: "canter",
    vehiclePlate: "BT 4521",
    vehicleMake: "Mitsubishi Canter",
    vehicleCapacity: 5000,
    currentLocation: { city: "Blantyre", district: "Blantyre City", region: "Southern", landmark: "Limbe Market" },
    isAvailable: true,
    completedTrips: 234,
    onTimeRate: 0.94,
    preferredRoutes: ["Blantyre-Lilongwe", "Blantyre-Zomba", "Blantyre-Mwanza"],
    hasGPS: true,
    unionMembership: "rtoa",
    preferredLanguage: "ny",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "t2",
    role: "transporter",
    name: "Grace Phiri",
    phone: "+265 888 345 678",
    whatsapp: "+265 888 345 678",
    rating: 4.9,
    totalRatings: 89,
    verified: true,
    verificationLevel: "full",
    rtoaMembership: "RTOA-2020-0234",
    vehicleType: "large_truck",
    vehiclePlate: "LL 7832",
    vehicleMake: "FUSO Fighter",
    vehicleCapacity: 12000,
    currentLocation: { city: "Lilongwe", district: "Lilongwe City", region: "Central", landmark: "Kanengo Industrial" },
    isAvailable: true,
    completedTrips: 178,
    onTimeRate: 0.97,
    preferredRoutes: ["Lilongwe-Mzuzu", "Lilongwe-Blantyre", "Lilongwe-Mchinji"],
    hasGPS: true,
    hasRefrigeration: false,
    unionMembership: "rtoa",
    preferredLanguage: "en",
    createdAt: new Date("2022-08-20"),
  },
  {
    id: "t3",
    role: "transporter",
    name: "Peter Mwale",
    phone: "+265 999 456 789",
    rating: 4.5,
    totalRatings: 67,
    verified: true,
    verificationLevel: "community",
    communityVouchers: ["t1", "t2", "sh1"],
    vehicleType: "pickup",
    vehiclePlate: "ZA 1234",
    vehicleMake: "Toyota Hilux",
    vehicleCapacity: 1500,
    currentLocation: { city: "Zomba", district: "Zomba City", region: "Southern", landmark: "Zomba Market" },
    isAvailable: true,
    completedTrips: 92,
    onTimeRate: 0.88,
    preferredRoutes: ["Zomba-Blantyre", "Zomba-Machinga", "Zomba-Mulanje"],
    hasGPS: false,
    unionMembership: "independent",
    preferredLanguage: "ny",
    createdAt: new Date("2023-06-10"),
  },
  {
    id: "t4",
    role: "transporter",
    name: "Chisomo Nyirenda",
    phone: "+265 884 567 890",
    whatsapp: "+265 884 567 890",
    rating: 4.7,
    totalRatings: 203,
    verified: true,
    verificationLevel: "rtoa",
    rtoaMembership: "RTOA-2019-0123",
    vehicleType: "flatbed",
    vehiclePlate: "MZ 9087",
    vehicleMake: "Hino 500",
    vehicleCapacity: 15000,
    currentLocation: { city: "Mzuzu", district: "Mzimba", region: "Northern", landmark: "Mzuzu Bus Depot" },
    isAvailable: true,
    completedTrips: 312,
    onTimeRate: 0.91,
    preferredRoutes: ["Mzuzu-Lilongwe", "Mzuzu-Karonga", "Mzuzu-Nkhata Bay"],
    hasGPS: true,
    unionMembership: "rtoa",
    preferredLanguage: "en",
    createdAt: new Date("2022-03-05"),
  },
  {
    id: "t5",
    role: "transporter",
    name: "Mercy Kamanga",
    phone: "+265 992 678 901",
    rating: 4.6,
    totalRatings: 45,
    verified: false,
    verificationLevel: "phone",
    vehicleType: "canter",
    vehiclePlate: "BT 2341",
    vehicleMake: "Isuzu NQR",
    vehicleCapacity: 3000,
    currentLocation: { city: "Blantyre", district: "Blantyre City", region: "Southern", landmark: "Ginnery Corner" },
    isAvailable: false,
    completedTrips: 56,
    onTimeRate: 0.85,
    preferredRoutes: ["Blantyre-Mulanje", "Blantyre-Thyolo"],
    hasGPS: false,
    unionMembership: "cooperative",
    cooperativeName: "Blantyre Haulage Association",
    preferredLanguage: "ny",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "t6",
    role: "transporter",
    name: "Kondwani Chirwa",
    phone: "+265 888 111 222",
    rating: 4.4,
    totalRatings: 38,
    verified: true,
    verificationLevel: "community",
    chiefReference: { name: "Chief Mwase", village: "Mwase", district: "Kasungu" },
    vehicleType: "medium_truck",
    vehiclePlate: "KU 5678",
    vehicleMake: "FUSO Canter",
    vehicleCapacity: 7000,
    currentLocation: { city: "Kasungu", district: "Kasungu", region: "Central", landmark: "Kasungu ADMARC" },
    isAvailable: true,
    completedTrips: 145,
    onTimeRate: 0.89,
    preferredRoutes: ["Kasungu-Lilongwe", "Kasungu-Mchinji"],
    hasGPS: false,
    unionMembership: "cooperative",
    cooperativeName: "Lilongwe Transport Cooperative",
    preferredLanguage: "ny",
    createdAt: new Date("2023-04-15"),
  },
]

export const mockShipments: Shipment[] = [
  {
    id: "s1",
    shipperId: "sh1",
    shipperName: "Malawi Grains Ltd",
    origin: {
      city: "Lilongwe",
      district: "Lilongwe City",
      region: "Central",
      landmark: "Kanengo ADMARC Depot",
      admarc: "Kanengo Main",
    },
    destination: {
      city: "Blantyre",
      district: "Blantyre City",
      region: "Southern",
      landmark: "Limbe Trading Centre",
    },
    cargoType: "maize",
    cargoDescription: "50kg bags of maize (100 bags) - Chimanga",
    cargoDescriptionNy: "Matumba a chimanga 50kg (100)",
    weight: 5000,
    requiredVehicleType: "large_truck",
    pickupDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    pickupTimeWindow: "06:00 - 10:00",
    price: 185000,
    currency: "MWK",
    paymentMethod: "airtel_money",
    status: "posted",
    isBackhaul: false,
    seasonalCategory: "maize_harvest",
    checkpoints: [
      { name: "Dedza", location: { city: "Dedza", district: "Dedza", region: "Central" } },
      { name: "Ntcheu", location: { city: "Ntcheu", district: "Ntcheu", region: "Central" } },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "s2",
    shipperId: "sh2",
    shipperName: "BuildMart Hardware",
    origin: {
      city: "Blantyre",
      district: "Blantyre City",
      region: "Southern",
      landmark: "Ginnery Corner",
    },
    destination: {
      city: "Zomba",
      district: "Zomba City",
      region: "Southern",
      landmark: "Zomba Market",
    },
    cargoType: "cement",
    cargoDescription: "Portland Cement 50kg bags (70 bags) and iron sheets",
    cargoDescriptionNy: "Simenti ndi malata",
    weight: 3500,
    requiredVehicleType: "canter",
    pickupDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    pickupTimeWindow: "08:00 - 12:00",
    price: 45000,
    currency: "MWK",
    paymentMethod: "cash",
    status: "posted",
    isBackhaul: true,
    backhaulDiscount: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "s3",
    shipperId: "sh1",
    shipperName: "Malawi Grains Ltd",
    origin: {
      city: "Mzuzu",
      district: "Mzimba",
      region: "Northern",
      landmark: "Mzuzu Market",
    },
    destination: {
      city: "Lilongwe",
      district: "Lilongwe City",
      region: "Central",
      landmark: "Area 25 Market",
    },
    cargoType: "perishable",
    cargoDescription: "Fresh vegetables - tomatoes and onions from Northern region",
    cargoDescriptionNy: "Masamba - matimati ndi anyezi",
    weight: 2000,
    requiredVehicleType: "refrigerated",
    pickupDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    pickupTimeWindow: "05:00 - 07:00",
    price: 320000,
    currency: "MWK",
    paymentMethod: "tnm_mpamba",
    status: "posted",
    isBackhaul: false,
    specialInstructions: "Temperature must be maintained at 4-8°C - Kuziziritsa ndi kofunikira",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "s4",
    shipperId: "sh3",
    shipperName: "Mwale Tobacco Estates",
    origin: {
      city: "Kasungu",
      district: "Kasungu",
      region: "Central",
      landmark: "Kasungu Tobacco Growers",
      admarc: "Kasungu ADMARC",
    },
    destination: {
      city: "Lilongwe",
      district: "Lilongwe City",
      region: "Central",
      landmark: "Kanengo Auction Floors",
    },
    cargoType: "tobacco",
    cargoDescription: "Burley tobacco bales (150 bales) for auction - Fodya",
    cargoDescriptionNy: "Fodya wa Burley (150 bales)",
    weight: 7500,
    requiredVehicleType: "large_truck",
    pickupDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    pickupTimeWindow: "04:00 - 08:00",
    price: 285000,
    currency: "MWK",
    paymentMethod: "bank_transfer",
    status: "posted",
    isBackhaul: false,
    seasonalCategory: "tobacco_auction",
    specialInstructions: "Handle with care - tobacco must stay dry",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "s5",
    shipperId: "sh4",
    shipperName: "Southern Importers Ltd",
    origin: {
      city: "Blantyre",
      district: "Blantyre City",
      region: "Southern",
      landmark: "Limbe Industrial",
    },
    destination: {
      city: "Mwanza",
      district: "Mwanza",
      region: "Southern",
      landmark: "Mwanza Border Post",
      isBorderTown: true,
      borderWith: "Mozambique",
    },
    cargoType: "general",
    cargoDescription: "Assorted goods for export via Beira Corridor",
    weight: 12000,
    requiredVehicleType: "large_truck",
    pickupDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    pickupTimeWindow: "06:00 - 09:00",
    price: 420000,
    currency: "MWK",
    paymentMethod: "bank_transfer",
    status: "posted",
    isBackhaul: false,
    borderCrossing: {
      required: true,
      borderPost: "Mwanza/Zobue",
      estimatedClearanceHours: 6,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "s6",
    shipperId: "sh5",
    shipperName: "Farmers World",
    origin: {
      city: "Blantyre",
      district: "Blantyre City",
      region: "Southern",
      landmark: "Maselema Warehouse",
    },
    destination: {
      city: "Kasungu",
      district: "Kasungu",
      region: "Central",
      landmark: "Kasungu ADMARC",
      admarc: "Kasungu Main",
    },
    cargoType: "fertilizer",
    cargoDescription: "NPK Fertilizer 50kg bags (200 bags) - Feteleza",
    cargoDescriptionNy: "Feteleza (200 matumba)",
    weight: 10000,
    requiredVehicleType: "large_truck",
    pickupDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    pickupTimeWindow: "07:00 - 11:00",
    price: 380000,
    currency: "MWK",
    paymentMethod: "airtel_money",
    status: "posted",
    isBackhaul: false,
    seasonalCategory: "fertilizer_import",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockBids: Bid[] = [
  {
    id: "b1",
    shipmentId: "s1",
    transporterId: "t2",
    transporterName: "Grace Phiri",
    transporterRating: 4.9,
    proposedPrice: 175000,
    message: "I can pick up early at 5:30 AM if needed. Have done this route 50+ times.",
    messageNy: "Nditha kutenga 5:30 mmawa. Ndayenda njira iyi maulendo oposa 50.",
    estimatedPickup: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    status: "pending",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "b2",
    shipmentId: "s1",
    transporterId: "t4",
    transporterName: "Chisomo Nyirenda",
    transporterRating: 4.7,
    proposedPrice: 180000,
    message: "Available and ready. GPS tracking enabled.",
    estimatedPickup: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    status: "pending",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: "b3",
    shipmentId: "s4",
    transporterId: "t6",
    transporterName: "Kondwani Chirwa",
    transporterRating: 4.4,
    proposedPrice: 270000,
    message: "I specialize in tobacco transport. Based in Kasungu, can pick up same day.",
    messageNy: "Ndimadziwa bwino kunyamula fodya. Ndili ku Kasungu, nditha kutenga lero.",
    estimatedPickup: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    status: "pending",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
]
